# Generated by Django 4.2.6 on 2023-10-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("datetime", models.DateTimeField()),
                ("department_id", models.IntegerField()),
                ("job_id", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Jobs",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("job", models.CharField(max_length=100)),
            ],
        ),
    ]
